// ///////////////////////////////////////////////////////////////////////////////
// Copyright [2023] [Richard Ikin]
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http: //www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// ///////////////////////////////////////////////////////////////////////////////

using System.Drawing;
using System.Text;

using LibGDXSharp.G2D;
using LibGDXSharp.Scenes.Listeners;
using LibGDXSharp.Scenes.Scene2D.Utils;

using Color = LibGDXSharp.Graphics.Color;

namespace LibGDXSharp.Scenes.Scene2D.UI;

/// A single-line text input field.
/// <para>
/// The preferred height of a text field is the height of the <see cref="Font"/>
/// and <see cref="TextFieldStyle.Background"/>. The preferred width of a text field is 150,
/// a relatively arbitrary size.
/// </para>
/// <para>
/// The text field will copy the currently selected text when ctrl+c is pressed, and
/// paste any text in the clipboard when ctrl+v is pressed. Clipboard functionality is
/// provided via the <see cref="IClipboard"/> interface.
/// </para>
/// <para>
/// The text field allows you to specify an <see cref="OnscreenKeyboard"/> for displaying
/// a softkeyboard and piping all key events generated by the keyboard to the text field.
/// There are two standard implementations, one for the desktop and one for Android.
/// The desktop keyboard is a stub, as a softkeyboard is not needed on the desktop. The
/// Android <see cref="OnScreenKeyboard"/> implementation will bring up the default IME.
/// </para>
[PublicAPI]
public class TextField : Widget
{
    protected const char CARRIAGE_RETURN = '\r';
    protected const char NEWLINE         = '\n';
    protected const char TAB             = '\t';
    protected const char BACKSPACE       = '\u0008';
    protected const char DELETE          = '\u007f';
    protected const char BULLET          = '\u0095';

    private readonly Vector2 _tmp1 = new();
    private readonly Vector2 _tmp2 = new();
    private readonly Vector2 _tmp3 = new();

    public static float keyRepeatInitialTime = 0.4f;
    public static float keyRepeatTime        = 0.1f;

    protected          string?       text;
    protected          int           cursor;
    protected          int           selectionStart;
    protected          bool          hasSelection;
    protected          bool          writeEnters;
    protected readonly GlyphLayout   layout         = new();
    protected readonly List< float > glyphPositions = new();
    protected          string?       displayText;
    protected          float         fontOffset;
    protected          float         textHeight;
    protected          float         textOffset;

    private TextFieldStyle?    _style;
    private string?            _messageText;
    private IClipboard?        _clipboard;
    private InputListener?     _inputListener;
//    private TextFieldListener? _listener;
//    private TextFieldFilter?   _filter;
//    private OnscreenKeyboard   _keyboard       = new DefaultOnscreenKeyboard();
    private bool               _focusTraversal = true;
    private bool               _onlyFontChars  = true;
    private bool               _disabled;
    private int                _textHAlign = Align.LEFT;
    private float              _selectionX;
    private float              _selectionWidth;

    private string?        _undoText = "";
    private long           _lastChangeTime;
    private bool           _passwordMode;
    private StringBuilder? _passwordBuffer;
    private char           _passwordCharacter = BULLET;

    private float _renderOffset;
    private int   _visibleTextStart;
    private int   _visibleTextEnd;
    private int   _maxLength;

    private float _blinkTime = 0.32f;
    private bool  _focused;
    private bool  _cursorOn;

    private bool _programmaticChangeEvents;

    public TextField( string? text, Skin skin )
        : this( text, skin.Get< TextFieldStyle >() )
    {
    }

    public TextField( string? text, Skin skin, string styleName )
        : this( text, ( TextFieldStyle )skin.Get< TextFieldStyle >( styleName ) )
    {
    }

    public TextField( string? text, TextFieldStyle style )
    {
        SetStyle( style );
        _clipboard = Gdx.App.Clipboard;
        Initialise();
        SetText( text );
        SetSize( GetPrefWidth(), GetPrefHeight() );
    }

    private void Initialise()
    {
    }

    public void SetStyle( TextFieldStyle style )
    {
    }

    protected void CalculateOffsets()
    {
    }

    public float GetPrefWidth() => 150;
    public float GetPrefHeight() => PrefHeight;
    
    protected int LetterUnderCursor( float x )
    {
        return 0;
    }

    protected bool IsWordCharacter( char c )
    {
        return false;
    }

    protected int[] WordUnderCursor( int at )
    {
        throw new NotImplementedException();
    }

    protected int[] WordUnderCursor( float x )
    {
        throw new NotImplementedException();
    }

    protected bool WithinMaxLength( int size )
    {
        return ( _maxLength <= 0 ) || ( size < _maxLength );
    }

    protected IDrawable? GetBackgroundDrawable()
    {
        return null;
    }

    public override void Draw( IBatch batch, float parentAlpha )
    {
    }

    protected float GetTextY( BitmapFont font, IDrawable? background )
    {
        return 0;
    }

    protected void DrawSelection( IDrawable selection, IBatch batch, BitmapFont font, float x, float y )
    {
    }

    protected void DrawText( IBatch batch, BitmapFont font, float x, float y )
    {
    }

    protected void DrawMessageText( IBatch batch, BitmapFont font, float x, float y, float maxWidth )
    {
    }

    protected void DrawCursor( IDrawable cursorPatch, IBatch batch, BitmapFont font, float x, float y )
    {
    }

    private void UpdateDisplayText()
    {
    }

    public void SetText( string? str )
    {
    }
    
    // ------------------------------------------------------------------------

    /// <summary>
    /// The style for a <see cref="TextField"/>.
    /// </summary>
    [PublicAPI]
    public class TextFieldStyle
    {
        public BitmapFont? Font               { get; set; }
        public Color?      FontColor          { get; set; }
        public Color?      FocusedFontColor   { get; set; }
        public Color?      DisabledFontColor  { get; set; }
        public IDrawable?  Background         { get; set; }
        public IDrawable?  FocusedBackground  { get; set; }
        public IDrawable?  DisabledBackground { get; set; }
        public IDrawable?  Cursor             { get; set; }
        public IDrawable?  Selection          { get; set; }
        public BitmapFont? MessageFont        { get; set; }
        public Color?      MessageFontColor   { get; set; }

        public TextFieldStyle()
        {
        }

        public TextFieldStyle( BitmapFont font,
                               Color fontColor,
                               IDrawable? cursor,
                               IDrawable? selection,
                               IDrawable? background )
        {
            this.Font       = font;
            this.FontColor  = fontColor;
            this.Cursor     = cursor;
            this.Selection  = selection;
            this.Background = background;
        }

        public TextFieldStyle( TextFieldStyle style )
        {
            Font = style.Font;

            if ( style.FontColor != null )
            {
                FontColor = new Color( style.FontColor );
            }

            if ( style.FocusedFontColor != null )
            {
                FocusedFontColor = new Color( style.FocusedFontColor );
            }

            if ( style.DisabledFontColor != null )
            {
                DisabledFontColor = new Color( style.DisabledFontColor );
            }

            Background         = style.Background;
            FocusedBackground  = style.FocusedBackground;
            DisabledBackground = style.DisabledBackground;
            Cursor             = style.Cursor;
            Selection          = style.Selection;

            MessageFont = style.MessageFont;

            if ( style.MessageFontColor != null )
            {
                MessageFontColor = new Color( style.MessageFontColor );
            }
        }
    }
}
